package LoginServer

const (
	CSM_WELCOME = 0
	SM_WELCOME2 = 70
	SM_SENDIP   = 3
	CM_WELCOME2 = 11

	CSM_REGISTER     = 2
	CM_REGISTER_DONE = 4
	CM_PLANET_DATA   = 66
	CS_PLANET_DATA   = 64
	CM_LOGIN         = 3
	CM_LWELCOME      = 5
	SM_REG_METHOD    = 6
	CSM_FACTION_DATA = 15

	CS_FRIEND_SELECT = 87
	SM_FRIEND_SELECT = 85
)
